Repository julioserafim/almoxarifado-v0.2.2, pull requests merged in 2020-05, with the labels that each got.

#37 Refatoração de duas god classes: em relatorio controller e entrada
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/META-INF/MANIFEST.MF
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/controller/RelatorioController.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/controller/RelatorioController2.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/model/ItemEntrada.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/model/ItemEntrada2.java
Labels: God Class

#32 Refatoração de Long Method em EntradaServiceImpl
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/impl/EntradaServiceImpl.java
Labels: Long Method

#25 Refatoração de 'Long Method' em 'SaidaController'
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/controller/SaidaController.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/SaidaService.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/impl/SaidaServiceImpl.java
Labels: Long Method

#24 Refatoração de 'Feature Envy' em 'UsuarioServiceImpl'
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/impl/UsuarioServiceImpl.java
Labels: Feature Envy

#31 Refatoração de Long Method em RelatorioController
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/controller/RelatorioController.java
Labels: Long Method

#23 Refatoração de 'God Class' em 'GerarRelatorio'
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/controller/RelatorioController.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/RelatorioService.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/impl/RelatorioServiceImpl.java
Labels: God Class

#22 Refatoração de 'God Class'
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/controller/MaterialController.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/MaterialService.java
  almoxarifado-v0.2.2/aplicacao/clinicas/src/main/java/ufc/npi/clinicas/service/impl/MaterialServiceImpl.java
Labels: God Class
